pfe_frontend_booking_create:
    pattern:  /booking/event/{slug}
    defaults: { _controller: "PfeBookingBundle:Frontend/Booking:new", locale: %locale% }
    requirements: { _method: post }

pfe_frontend_booking_payment:
    pattern:  /booking/payment/{token}
    defaults: { _controller: "PfeBookingBundle:Frontend/Booking:payment" }