parameters:
#    pfe_event.example.class: Pfe\Bundle\EventBundle\Example

services:
#    pfe_event.example:
#        class: %pfe_event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
