pfe_web_frontend_homepage:
    pattern:  /
    defaults: { _controller: PfePageBundle:Frontend/Page:home, locale: %locale% }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_security:
    resource: "@PfeCustomerBundle/Resources/config/routing/frontend/security.yml"

pfe_web_frontend_event:
    resource: "@PfeEventBundle/Resources/config/routing/frontend/event.yml"

pfe_web_frontend_booking:
    resource: "@PfeBookingBundle/Resources/config/routing/frontend/routing.yml"
    prefix: /register

pfe_web_frontend_page:
    pattern:  /{locale}/{slug}
    defaults: { _controller: PfePageBundle:Frontend/Page:show, locale: %locale% }