pfe_web_backend_dashboard:
    pattern:  /dashboard
    defaults: { _controller: PfeWebBundle:Backend/Dashboard:index  }

pfe_web_backend_customer_bundle:
    resource: "@PfeCustomerBundle/Resources/config/routing/backend/routing.yml"