pfe_web_backend_dashboard:
    pattern:  /dashboard
    defaults: { _controller: PfeWebBundle:Backend/Dashboard:index  }

pfe_web_backend_customer:
    resource: "@PfeCustomerBundle/Resources/config/routing/backend/routing.yml"
    prefix: /customer

pfe_page_bundle:
   resource: "@PfePageBundle/Resources/config/routing/backend/routing.yml"
   prefix: /page

pfe_event_bundle:
   resource: "@PfeEventBundle/Resources/config/routing/backend/routing.yml"
   prefix: /event