pfe_page:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: pfe_page_index, permanent: true }

pfe_page_index:
    pattern:  /index
    defaults: { _controller: "PfePageBundle:Backend/Page:index" }

pfe_page_show:
    pattern:  /{token}/show
    defaults: { _controller: "PfePageBundle:Backend/Page:show" }

pfe_page_new:
    pattern:  /new
    defaults: { _controller: "PfePageBundle:Backend/Page:new" }

pfe_page_create:
    pattern:  /create
    defaults: { _controller: "PfePageBundle:Backend/Page:create" }
    requirements: { _method: post }

pfe_page_edit:
    pattern:  /{token}/edit
    defaults: { _controller: "PfePageBundle:Backend/Page:edit" }

pfe_page_update:
    pattern:  /{token}/update
    defaults: { _controller: "PfePageBundle:Backend/Page:update" }
    requirements: { _method: post|put }

pfe_page_delete:
    pattern:  /{token}/delete
    defaults: { _controller: "PfePageBundle:Backend/Page:delete" }
    requirements: { _method: post|delete }