pfe_menu:
    resource: "@PfeMenuBundle/Resources/config/routing.yml"
    prefix:   /

pfe_bundle_menu:
    resource: "@PfeBundleMenuBundle/Resources/config/routing.yml"
    prefix:   /

pfe_events_web:
    resource: "@PfeWebBundle/Resources/config/routing.yml"