menu:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: menu, permanent: true }

menu_index:
    pattern:  /index
    defaults: { _controller: "PfeMenuBundle:Menu:index" }

menu_show:
    pattern:  /{token}/show
    defaults: { _controller: "PfeMenuBundle:Menu:show" }

menu_new:
    pattern:  /new
    defaults: { _controller: "PfeMenuBundle:Menu:new" }

menu_create:
    pattern:  /create
    defaults: { _controller: "PfeMenuBundle:Menu:create" }
    requirements: { _method: post }

menu_edit:
    pattern:  /{token}/edit
    defaults: { _controller: "PfeMenuBundle:Menu:edit" }

menu_update:
    pattern:  /{token}/update
    defaults: { _controller: "PfeMenuBundle:Menu:update" }
    requirements: { _method: post|put }

menu_delete:
    pattern:  /{token}/delete
    defaults: { _controller: "PfeMenuBundle:Menu:delete" }
    requirements: { _method: post|delete }
