pfe_event_category:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: pfe_event_category_index, permanent: true }

pfe_event_category_index:
    pattern:  /index
    defaults: { _controller: "PfeEventBundle:Backend/Category:index" }

pfe_event_category_show:
    pattern:  /{token}/show
    defaults: { _controller: "PfeEventBundle:Backend/Category:show" }

pfe_event_category_new:
    pattern:  /new
    defaults: { _controller: "PfeEventBundle:Backend/Category:new" }

pfe_event_category_create:
    pattern:  /create
    defaults: { _controller: "PfeEventBundle:Backend/Category:create" }
    requirements: { _method: post }

pfe_event_category_edit:
    pattern:  /{token}/edit
    defaults: { _controller: "PfeEventBundle:Backend/Category:edit" }

pfe_event_category_update:
    pattern:  /{token}/update
    defaults: { _controller: "PfeEventBundle:Backend/Category:update" }
    requirements: { _method: post|put }

pfe_event_category_delete:
    pattern:  /{token}/delete
    defaults: { _controller: "PfeEventBundle:Backend/Category:delete" }
    requirements: { _method: post|delete }
