parameters:
    pfe_locale_listener.class: Pfe\Bundle\WebBundle\Listener\LocaleListener

services:
    ws_locale_listener:
        class: %pfe_locale_listener.class%
        arguments: ["%kernel.default_locale%"]
        calls:
            - [ setContainer, [@service_container] ]
        tags:
            - { name: kernel.event_subscriber }
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]