parameters:
#    pfe_web.example.class: Pfe\Bundle\WebBundle\Example

services:
#    pfe_web.example:
#        class: %pfe_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
