parameters:
#    pfe_booking.example.class: Pfe\Bundle\BookingBundle\Example

services:
#    pfe_booking.example:
#        class: %pfe_booking.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
