<?php

namespace Pfe\Bundle\EventBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTranslationRepository extends EntityRepository
{
}
