parameters:
    pfe_customer.registration.class: Pfe\Bundle\CustomerBundle\Form\CustomerRegistration

services:
    pfe_customer.registration.form:
        class: %pfe_customer.registration.class%
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: pfe_customer_registration }